services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wildlife_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"


